#!/bin/sh

# Welcome to the thoughtbot laptop script!
# Be prepared to turn your laptop (or desktop, no haters here)
# into an awesome development machine.

# creation d'une cle si necessaire 
echo "Checking for SSH key, generating one if it doesn't exist ..."
[[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

# copy dans github
echo "Copying public key to clipboard. Paste it into your Github account ..."
[[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
open https://github.com/settings/ssh

mkdir -p ~/Library/LaunchAgents # Will put startup scripts here

echo "Installing Redis, a good key-value database ..."
brew install redis
echo "Configuring Redis so that it starts at startup ..."
REDIS_CURRENT_PLIST=~/Library/LaunchAgents/homebrew.mxcl.redis.plist
[[ -f ~/.ssh/id_rsa.pub ]] || launchctl unload -w REDIS_CURRENT_PLIST

REDIS_PLIST=`ls /usr/local/Cellar/redis/*/homebrew.mxcl.redis.plist | tail -1`
echo "Copying $REDIS_PLIST to ~/Library/LaunchAgents/"
cp $REDIS_PLIST ~/Library/LaunchAgents/ 
launchctl load -w $REDIS_CURRENT_PLIST

echo "Installing MongoDB, a good NoSQL database ..."
brew install mongodb
echo "Configuring MongoDB so that it starts at startup ..."
MONGO_CURRENT_PLIST=~/Library/LaunchAgents/homebrew.mxcl.mongodb.plist
[[ -f ~/.ssh/id_rsa.pub ]] || launchctl unload -w $MONGO_CURRENT_PLIST

MONGO_PLIST=`ls /usr/local/Cellar/mongodb/*/homebrew.mxcl.mongodb.plist | tail -1`
echo "Copying $MONGO_PLIST to ~/Library/LaunchAgents/"
echo "Copying $MONGO_CONFIG to /usr/local/etc/"
cp $MONGO_PLIST ~/Library/LaunchAgents/
if [[ ! -d /data/db ]]; then
  echo "Need your password to sudo to create the folder /data/db"; 
  sudo mkdir -p /data/db; 
  sudo chown `id -u` /data/db 
fi
launchctl load -w $MONGO_CURRENT_PLIST 

echo "Installing NodeJS ..."
brew install node

echo "Installing ack, a good way to search through files ..."
brew install ack

echo "Install ssh-copy-id, because you just want to type your password once..."
brew install ssh-copy-id
  
echo "Installing tmux, a good way to save project state and switch between projects ..."
brew install tmux


echo "Installing automake, which is need for doing rvm install --with-gcc=clang"
brew install automake

echo "Installing RVM (Ruby Version Manager) ..."
curl -L https://get.rvm.io | bash -s stable --ruby
# RVM
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"


echo "Installing $RUBY_VERSION stable and making it the default Ruby ..."
rvm install 1.9 --with-gcc=clang
rvm use 1.9 --default

echo "Installing Rails to write and run web applications ..."
gem install rails --no-rdoc --no-ri --version '~> 3.2.21'

echo "Installing Bundler ..."
gem install bundler

echo "Installing the foreman gem for serving your Rails apps in development mode ..."
gem install foreman --no-rdoc --no-ri

#empties the .zprofile (avoid conflicts for RVM)
echo '' > ~/.zprofile 


# Setting up Cornis defaults code directories
echo "Setting up ~/code directory. That's where you gonna work buddy ..."
mkdir -p ~/code


# Setting up some useful links
echo 'alias subl="/Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl"' >> ~/.zprofile 
echo 'alias stt="subl ."' >> ~/.zprofile


